- description: ""
  label: "Module Team"
  name: "module_team"
  sort: 106
  listed: true
  hasRoute: true
  showAsTable: false
  parent: null
  view: "/views/module_team.tpl"
  content: "/content/module_team.yaml"
  fields:
    - name: "hero_header_text"
      label: "hero header text"
      description: ""
      datatype: "text"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "hero_description"
      label: "hero description"
      description: ""
      datatype: "text"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "hero_image_background"
      label: "Hero Image Background"
      description: ""
      datatype: "images"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
- description: ""
  label: "Module Team Items"
  name: "module_team_items"
  sort: 108
  listed: true
  hasRoute: false
  showAsTable: false
  parent: "module_team"
  content: "/content/module_team_items.yaml"
  fields:
    - name: "team_sort"
      label: "team sort"
      description: ""
      datatype: "sort"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "image"
      label: "image"
      description: ""
      datatype: "images"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "name"
      label: "name"
      description: ""
      datatype: "text"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "career_title"
      label: "career title"
      description: ""
      datatype: "text"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "description"
      label: "description"
      description: ""
      datatype: "text"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "social_1"
      label: "social media 1"
      description: ""
      datatype: "link"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "social_icon_1"
      label: "social icon 1"
      description: ""
      datatype: "dropdown"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
        options:
          bi-discord: "Discord"
          bi-envelope: "Email"
          bi-facebook: "Facebook"
          bi-github: "Github"
          bi-google: "Google"
          bi-instagram: "Instagram"
          bi-link-45deg: "Normal Link"
          bi-linkedin: "LinkedIN"
          bi-skype: "Skype"
          bi-slack: "Slack"
          bi-telegram: "Telegram"
          bi-twitch: "Twitch"
          bi-twitter: "Twitter"
          bi-whatsapp: "Whatsappp"
          bi-youtube: "Youtube"
    - name: "social_2"
      label: "social media 2"
      description: ""
      datatype: "link"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "social_icon_2"
      label: "social icon 2"
      description: ""
      datatype: "dropdown"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
        options:
          bi-discord: "Discord"
          bi-envelope: "Email"
          bi-facebook: "Facebook"
          bi-github: "Github"
          bi-google: "Google"
          bi-instagram: "Instagram"
          bi-link-45deg: "Normal Link"
          bi-linkedin: "LinkedIN"
          bi-skype: "Skype"
          bi-slack: "Slack"
          bi-telegram: "Telegram"
          bi-twitch: "Twitch"
          bi-twitter: "Twitter"
          bi-whatsapp: "Whatsappp"
          bi-youtube: "Youtube"
    - name: "social_3"
      label: "social media 3"
      description: ""
      datatype: "link"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "social_icon_3"
      label: "social icon 3"
      description: ""
      datatype: "dropdown"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
        options:
          bi-discord: "Discord"
          bi-envelope: "Email"
          bi-facebook: "Facebook"
          bi-github: "Github"
          bi-google: "Google"
          bi-instagram: "Instagram"
          bi-link-45deg: "Normal Link"
          bi-linkedin: "LinkedIN"
          bi-skype: "Skype"
          bi-slack: "Slack"
          bi-telegram: "Telegram"
          bi-twitch: "Twitch"
          bi-twitter: "Twitter"
          bi-whatsapp: "Whatsappp"
          bi-youtube: "Youtube"
    - name: "social_4"
      label: "social media 4"
      description: ""
      datatype: "link"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
    - name: "social_icon_4"
      label: "social icon 4"
      description: ""
      datatype: "dropdown"
      sort: 10000
      required: false
      relationship: null
      settings:
        list: true
        options:
          bi-discord: "Discord"
          bi-envelope: "Email"
          bi-facebook: "Facebook"
          bi-github: "Github"
          bi-google: "Google"
          bi-instagram: "Instagram"
          bi-link-45deg: "Normal Link"
          bi-linkedin: "LinkedIN"
          bi-skype: "Skype"
          bi-slack: "Slack"
          bi-telegram: "Telegram"
          bi-twitch: "Twitch"
          bi-twitter: "Twitter"
          bi-whatsapp: "Whatsappp"
          bi-youtube: "Youtube"
